name: ArcIamStoryPlugin
main: com.github.miniyosshi.arciamstoryplugin.ArcIamStoryPlugin
version: 1.0
commands:
  
  deletearea:
    descripstion: Delete an area.
  
  reloadcsv:
    descripstion: Reload all csv files.
  
  showarea:
    descripstion: See set areas.
  
  setarea:
    description: Set your location as the one corner of an area.
    usage: "/setarea [name of area] 0or1"
    
